language: android

jdk:
  - openjdk8

env:
  - TERM=dumb

android:
  components:
    - tools
    - platform-tools
    - tools
    - build-tools-28.0.2
    - android-28
    - extra-android-support
    - extra-android-m2repository
    - extra-google-m2repository
    - addon

  licenses:
    - android-sdk-license-.+
    - android-sdk-preview-license-.+

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

script:
  - ./gradlew build

deploy:
  provider: releases
  api_key: $GITHUB_ACCESS_TOKEN
  file:
    - build/outputs/apk/obsqr-zbar-debug.apk
    - build/outputs/apk/obsqr-gmsvision-debug.apk
  skip_cleanup: true
  on:
    tags: true